//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbapsbEntities : DbContext
    {
        public dbapsbEntities()
            : base("name=dbapsbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbDespesas> tbDespesas { get; set; }
        public virtual DbSet<tbDespesasCategoria> tbDespesasCategoria { get; set; }
        public virtual DbSet<tbDespesaTipo> tbDespesaTipo { get; set; }
    }
}
