//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBancos()
        {
            this.tbClinicas = new HashSet<tbClinicas>();
            this.tbProfissionaisBancos = new HashSet<tbProfissionaisBancos>();
        }
    
        public int IdBanco { get; set; }
        public string ccBanco { get; set; }
        public short cvCodBanco { get; set; }
        public short cvStatus { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbClinicas> tbClinicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProfissionaisBancos> tbProfissionaisBancos { get; set; }
    }
}
