//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClinicaProfissional
    {
        public int IdClinicaProfissional { get; set; }
        public int idClinica { get; set; }
        public int idProfissional { get; set; }
        public decimal cvTaxaProfissional { get; set; }
        public Nullable<int> idObservacao { get; set; }
        public Nullable<short> cvStatus { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
        public Nullable<System.DateTime> cdDataAlteracao { get; set; }
        public string ccAlteradoPor { get; set; }
    
        public virtual tbClinicas tbClinicas { get; set; }
        public virtual tbObservacoes tbObservacoes { get; set; }
        public virtual tbProfissionais tbProfissionais { get; set; }
    }
}
