//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDespesaTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDespesaTipo()
        {
            this.tbDespesas = new HashSet<tbDespesas>();
        }
    
        public int idTipo { get; set; }
        public string ccTipo { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<bool> cbStatus { get; set; }
        public string ccUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDespesas> tbDespesas { get; set; }
        public virtual tbDespesasCategoria tbDespesasCategoria { get; set; }
    }
}
