//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDespesasCategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDespesasCategoria()
        {
            this.tbDespesaTipo = new HashSet<tbDespesaTipo>();
        }
    
        public int idCategoria { get; set; }
        public string ccCategoria { get; set; }
        public Nullable<System.DateTime> cdCriacao { get; set; }
        public string ccUsuario { get; set; }
        public Nullable<bool> cbStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDespesaTipo> tbDespesaTipo { get; set; }
    }
}
