//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDespesas
    {
        public int idDespesas { get; set; }
        public int idTipo { get; set; }
        public double cvValor { get; set; }
        public Nullable<System.DateTime> cdData { get; set; }
        public Nullable<bool> cbArquivado { get; set; }
        public Nullable<bool> cbStatus { get; set; }
        public Nullable<int> IdObservacao { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
        public string UserName { get; set; }
    
        public virtual tbObservacoes tbObservacoes { get; set; }
        public virtual tbDespesaTipo tbDespesaTipo { get; set; }
    }
}
