//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEndereco
    {
        public int IdEndereco { get; set; }
        public string ccEndereco { get; set; }
        public string ccBairro { get; set; }
        public Nullable<int> cvCEP { get; set; }
        public string ccUF { get; set; }
        public string ccCidade { get; set; }
        public int idProfissional { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
    
        public virtual tbProfissionais tbProfissionais { get; set; }
    }
}
