//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEspecialidade
    {
        public int idEspecialidade { get; set; }
        public string Especialidade { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
    }
}
