//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbImport01
    {
        public string PROFISSIONAL { get; set; }
        public string CL_NICA_OU_HOSPITAL { get; set; }
        public string TAXA { get; set; }
        public string BANCO { get; set; }
        public string C_D_BANCO { get; set; }
        public string AG_NCIA { get; set; }
        public string CC { get; set; }
        public string CPF { get; set; }
        public string T_TULO_DE_ELEITOR { get; set; }
        public string OBSERVA_O { get; set; }
        public Nullable<int> idProfissional { get; set; }
        public Nullable<int> idClinica { get; set; }
    }
}
