//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLogArquivamento
    {
        public int idLog { get; set; }
        public string UserName { get; set; }
        public Nullable<int> qtdRegistros { get; set; }
        public Nullable<System.DateTime> dtCorte { get; set; }
        public Nullable<System.DateTime> dtExecucao { get; set; }
    }
}
