//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProfissionalArquivo
    {
        public int idArquivo { get; set; }
        public int idProfissional { get; set; }
        public string ccNomeArquivo { get; set; }
        public byte[] binaryFile { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
    
        public virtual tbProfissionais tbProfissionais { get; set; }
    }
}
