//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProfissionaisBancos
    {
        public int IdProfissionalBanco { get; set; }
        public string ccAgencia { get; set; }
        public string ccConta { get; set; }
        public string ccOperacao { get; set; }
        public int idProfissional { get; set; }
        public int idBanco { get; set; }
        public Nullable<bool> cvStatus { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
    
        public virtual tbBancos tbBancos { get; set; }
        public virtual tbProfissionais tbProfissionais { get; set; }
    }
}
