//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProfissionaisDados
    {
        public int IdDadoProfissional { get; set; }
        public int idProfissional { get; set; }
        public string ccFormacao { get; set; }
        public string ccPosGraduacao { get; set; }
        public string ccEspecialidade { get; set; }
        public string ccConselho { get; set; }
        public Nullable<long> cvNumInscricao { get; set; }
        public Nullable<long> cvTitulo { get; set; }
        public Nullable<short> cvTituloZona { get; set; }
        public Nullable<short> cvTituloSecao { get; set; }
        public Nullable<long> cvReservista { get; set; }
        public Nullable<long> cvPIS { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
    
        public virtual tbProfissionais tbProfissionais { get; set; }
    }
}
