//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProfissionais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProfissionais()
        {
            this.tbClinicaProfissional = new HashSet<tbClinicaProfissional>();
            this.tbEndereco = new HashSet<tbEndereco>();
            this.tbProfissionaisBancos = new HashSet<tbProfissionaisBancos>();
            this.tbProfissionaisDados = new HashSet<tbProfissionaisDados>();
            this.tbProfissionalArquivo = new HashSet<tbProfissionalArquivo>();
            this.tbProfissionalRepasse = new HashSet<tbProfissionalRepasse>();
        }
    
        public int IdProfissional { get; set; }
        public string ccNome { get; set; }
        public string ccSexo { get; set; }
        public string ccNaturalUF { get; set; }
        public string ccNaturalCidade { get; set; }
        public string ccEstadoCivil { get; set; }
        public string ccEmail { get; set; }
        public short cvStatus { get; set; }
        public string ccCriadoPor { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
        public string ccAlteradoPor { get; set; }
        public Nullable<System.DateTime> cdDataAlteracao { get; set; }
        public Nullable<int> IdObservacao { get; set; }
        public string RGNum { get; set; }
        public string RGEmissor { get; set; }
        public Nullable<System.DateTime> RGdtEmissao { get; set; }
        public string CPFNum { get; set; }
        public Nullable<long> cvTelefone { get; set; }
        public Nullable<long> cvCelular { get; set; }
        public string nomePai { get; set; }
        public string nomeMae { get; set; }
        public string nomeConjuge { get; set; }
        public Nullable<System.DateTime> cdDataNascimento { get; set; }
        public Nullable<bool> cbAutoCadastro { get; set; }
        public Nullable<System.DateTime> cdFiliacao { get; set; }
        public Nullable<System.DateTime> cdPgtoTaxa { get; set; }
        public Nullable<System.DateTime> cdRegCartorio { get; set; }
        public Nullable<long> cvCNH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbClinicaProfissional> tbClinicaProfissional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEndereco> tbEndereco { get; set; }
        public virtual tbObservacoes tbObservacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProfissionaisBancos> tbProfissionaisBancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProfissionaisDados> tbProfissionaisDados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProfissionalArquivo> tbProfissionalArquivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProfissionalRepasse> tbProfissionalRepasse { get; set; }
    }
}
