//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProfissionalRepasse
    {
        public int idRepasse { get; set; }
        public int idReceita { get; set; }
        public int IdProfissional { get; set; }
        public Nullable<int> IdObservacao { get; set; }
        public float cvValor { get; set; }
        public string ccStatus { get; set; }
        public Nullable<System.DateTime> dataRepasse { get; set; }
        public string ccCriadoPor { get; set; }
        public Nullable<float> cvTaxaProfissional { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
        public Nullable<decimal> cvValorRepasse { get; set; }
    
        public virtual tbObservacoes tbObservacoes { get; set; }
        public virtual tbProfissionais tbProfissionais { get; set; }
        public virtual tbReceitas tbReceitas { get; set; }
    }
}
