//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTelefones
    {
        public int IdTelefone { get; set; }
        public int cvTelefone { get; set; }
        public string ccTipo { get; set; }
        public Nullable<System.DateTime> cdDataCriacao { get; set; }
    }
}
