//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReceitas
    {
        public int idReceita { get; set; }
        public Nullable<decimal> cvValorUsado { get; set; }
        public Nullable<decimal> cvValorRepassado { get; set; }
        public Nullable<System.DateTime> dtRepasse { get; set; }
        public string status { get; set; }
    }
}
