//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwResumoReceitas
    {
        public int idReceita { get; set; }
        public Nullable<decimal> cvValor { get; set; }
        public Nullable<decimal> cvValorPago { get; set; }
        public Nullable<decimal> cvValorRepassado { get; set; }
        public Nullable<decimal> cvValorDisponivel { get; set; }
        public Nullable<System.DateTime> cdEmissao { get; set; }
        public Nullable<System.DateTime> cdPagamento { get; set; }
        public Nullable<System.DateTime> cdRepasse { get; set; }
        public Nullable<decimal> cvDesconto { get; set; }
        public Nullable<int> cvNF { get; set; }
        public string observacao { get; set; }
        public Nullable<bool> cbIssRetido { get; set; }
        public string ccApelido { get; set; }
        public Nullable<long> cvCNPJ { get; set; }
        public Nullable<System.DateTime> cdPrevistaPgto { get; set; }
        public Nullable<decimal> cvDescontoValor { get; set; }
        public Nullable<float> cvISS { get; set; }
        public Nullable<decimal> cvISSValor { get; set; }
        public string Status { get; set; }
    }
}
