<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Configuracoes.aspx.cs" Inherits="Site.Cadastros.Configurações" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
        <div class="col">
            <h2 style="text-align: center" id="configTitle">Configurações</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <a class="nav-link active" id="v-pills-despesas-tab" data-toggle="pill" href="#v-pills-despesas" role="tab" aria-controls="v-pills-despesas" aria-selected="true">Despesas</a>
                <a class="nav-link" id="v-pills-receitas-tab" data-toggle="pill" href="#v-pills-receitas" role="tab" aria-controls="v-pills-receitas" aria-selected="false">Receitas</a>
                <a class="nav-link" id="v-pills-clinicas-tab" data-toggle="pill" href="#v-pills-clinicas" role="tab" aria-controls="v-pills-clinicas" aria-selected="false">Clínicas</a>
                <a class="nav-link" id="v-pills-medicos-tab" data-toggle="pill" href="#v-pills-medicos" role="tab" aria-controls="v-pills-medicos" aria-selected="false">Médicos</a>
            </div>
        </div>
        <div class="col-md-10">
            <div class="tab-content" id="v-pills-tabContent">
                <div class="tab-pane fade show active" id="v-pills-despesas" role="tabpanel" aria-labelledby="v-pills-despesas-tab">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <h4>Categorias de Despesas</h4>
                                <hr />
                                <br />
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#categoriaModal">
                                    Nova Categoria
                                </button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <asp:GridView runat="server" ID="gvCategoriasDespesas" CssClass="table table-hover table-striped table-sm" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="gvCategoriasDespesas_RowDeleting" OnPreRender="gvCategoriasDespesas_PreRender">
                                    <Columns>
                                        <asp:BoundField HeaderText="ID" DataField="idCategoria" ItemStyle-CssClass="rowID" />
                                        <asp:BoundField HeaderText="Categoria" DataField="ccCategoria" />
                                        <asp:BoundField HeaderText="Criado em" DataField="cdCriacao" DataFormatString="{0:d}" />
                                        <asp:BoundField HeaderText="Criado por" DataField="ccUsuario" />
                                    </Columns>
                                </asp:GridView>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <asp:TreeView runat="server" ID="tvCategoriasDespesas">
                                    <HoverNodeStyle ForeColor="Red" />
                                    <SelectedNodeStyle ForeColor="Green" />
                                    <NodeStyle ForeColor="Pink" />
                                    <Nodes>
                                    </Nodes>
                                </asp:TreeView>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <h4>Tipos de Despesas</h4>
                                <hr />
                                <br />
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#tipoModal">
                                    Novo Tipo
                                </button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <asp:GridView runat="server" ID="gvtiposDespesas" CssClass="table table-hover table-striped table-sm" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="gvtiposDespesas_RowDeleting">
                                    <Columns>
                                        <asp:BoundField HeaderText="ID" DataField="idTipo" ItemStyle-CssClass="rowID" />
                                        <asp:BoundField HeaderText="Categoria" DataField="ccCategoria" />
                                        <asp:BoundField HeaderText="Tipo" DataField="ccTipo" />
                                        <asp:BoundField HeaderText="Criado em" DataField="cdDataCriacao" DataFormatString="{0:d}" />
                                    </Columns>
                                </asp:GridView>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="tab-pane fade" id="v-pills-receitas" role="tabpanel" aria-labelledby="v-pills-receitas-tab">Receitas</div>
                <div class="tab-pane fade" id="v-pills-clinicas" role="tabpanel" aria-labelledby="v-pills-clinicas-tab">Clínicas</div>
                <div class="tab-pane fade" id="v-pills-medicos" role="tabpanel" aria-labelledby="v-pills-medicos-tab">Médicos</div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="categoriaModal" tabindex="-1" role="dialog" aria-labelledby="categoriaModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="categoriaModalLabel">Nova Categoria</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <label>Categoria: </label>
                    <asp:TextBox runat="server" ID="tbNovaCategoria" CssClass="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <%--<button type="button" class="btn btn-primary">Salvar</button>--%>
                    <asp:Button Text="Salvar" ID="btnSalvarCategoria" runat="server" CssClass="btn btn-primary" OnClick="btnSalvarCategoria_Click" />
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="tipoModal" tabindex="-1" role="dialog" aria-labelledby="tipoModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="tipoModalLabel">Novo Tipo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <label>Categoria Pai:</label>
                    <asp:DropDownList runat="server" ID="dpCategoriaPai" CssClass="form-control" DataSourceID="DSCategorias">
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="DSCategorias" runat="server" ConnectionString="<%$ ConnectionStrings:Dados %>" SelectCommand="SELECT [idCategoria], [ccCategoria] FROM [tbDespesasCategoria] WHERE ([idCategoriaPai] = @idCategoriaPai)">
                        <SelectParameters>
                            <asp:Parameter DefaultValue="0" Name="idCategoriaPai" Type="Int32" />
                        </SelectParameters>
                    </asp:SqlDataSource>

                    <br />

                    <label>Nova Categoria:</label>
                    <asp:DropDownList runat="server" ID="dpCategorias" CssClass="form-control" DataTextField="ccCategoria" DataValueField="idCategoria">
                    </asp:DropDownList>
                    <br />
                    <label>Tipo:</label>
                    <asp:TextBox runat="server" ID="tbNovoTipo" CssClass="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <asp:Button Text="Salvar" ID="btnSalvarTipo" runat="server" CssClass="btn btn-primary" OnClick="btnSalvarTipo_Click" />
                </div>
            </div>
        </div>
    </div>
</asp:Content>
